experiment: synrm_fast_tries
setup_matplotlib: False  # Show plots and visualization

matfile_path: /exchange/jrettberg/aphin/SynRM/SynRM4ApHIN.mat

# %% General identification framework settings
load_network: False  # train the network or load a pre-trained one

# for reproducability
seed: 100

# filter data (using a savgol filter)
filter_data: False 
# %% Disc brake data settings (get information from loaded data)
n_u: 3      # number of inputs
# n_mu: 2     # number of parameters (not varying inputs)

# scaling
# scaling_values: [1,1,1,1] 
# domain_split_vals: (list) integers that define the number of dofs for each domain, sum of all values needs to conincide with n_dn. If {None} it is considered as a single domain
domain_split_vals: [3,72,5,20,5,20] 
domain_names: ["eta","phi","rigid_body","elastic_modes","Drigid_body","Delastic_modes"]
desired_bounds: [0, 1]   # desired bounds after scaling for u and mu


# %% identification settings
r: 10 #  reduced order
use_pca: False  # use PCA for the input
n_pca: 20  # number of PCA components
pca_scaling: True  # scale the PCA components
pca_comparison: True
pca_only: False  # only use PCA components without nonlinear autoencoder
l_rec: 1 #  loss weight for the reconstruction
l_dz: 0.01 #  loss weight for the dz
l_dx: 0.0000001 #  loss weight for the dx
l1: 0.0000000001  # L1 regularization
l2: 0  # L2 regularization
n_epochs: 5000 #  number of epochs
batch_size: 256  # batch size
layer_sizes_ph: # layer sizes
  - 32  # first layer
  - 32  # second layer
  - 32  # third layer
layer_sizes_ae: # layer sizes
  - 64  # first layer
  - 32 # second layer
  - 16  # third layer
activation_ae: elu  # activation function
activation_ph: elu  # activation function
lr: 0.00025  # learning rate
tensorboard: False  # Save model information for analysis in tensorboard