model_name: msd

experiment: lti # name of the experiment {lti, ph}
sim_name: MSD_Qeye_ph_input_siso.npz # name of data  msd_state_ICrand_Qeye_autonomous_n3_m4.npz
load_network: True  # train the network or load the last pre-trained one

seed: 1  # For reproducibility

save_plots: False

# train-test split
test_size: 0.06

tensorboard: False  # Save model information for analysis in tensorboard

# scaling bounds for mu
desired_bounds: [0, 1]  # desired bounds after scaling for u and mu

# time extrapolation
trunc_time_ratio: 0.8  # ratio of time steps to be truncated for time extrapolation

# %% identification settings
l1: 0.000001  # L1 regularization
l2: 0  # L2 regularization
n_epochs: 1500  # number of epochs
batch_size: 64  # batch size
layer_sizes_ph: # layer sizes
  - 16  # first layer
  - 32  # second layer
  - 64  # third layer
activation_ph: selu  # activation function
lr: 0.00003  # learning rate
