model_name: msd

experiment: msd_matrix_interpolation_more_data2 # name of the experiment
sim_name: MSD_Qeye_ph_input_siso_matrix_interpolation.npz # name of data  msd_state_ICrand_Qeye_autonomous_n3_m4.npz
load_network: True  # train the network or load the last pre-trained one

seed: 123  # For reproducibility

setup_matplotlib: False

layer: "ph_layer" # ph_layer | phq_layer

# train-test split
# test_size: 0.25

tensorboard: False  # Save model information for analysis in tensorboard

# scaling bounds for mu
desired_bounds: [0, 1]  # desired bounds after scaling for u and mu

# %% identification settings
l1: 0.0000001  # L1 regularization
l2: 0  # L2 regularization
n_epochs: 1500 # number of epochs
batch_size: 64  # batch size
layer_sizes_ph: # layer sizes
  - 16  # first layer
  - 32  # second layer
  - 64  # third layer
activation_ph: selu  # activation function
lr: 0.00005  # learning rate

# matrix interpolation
ansatz: linear  # linear |