model_name: msd

experiment: msd_phin_lti_mi # name of the experiment
sim_name: MSD_Qeye_ph_input_siso.npz # name of data  msd_state_ICrand_Qeye_autonomous_n3_m4.npz
load_network: False  # train the network or load the last pre-trained one

seed: 1  # For reproducibility

save_plots: True

ph_layer: "phq_layer" # ph_layer | phq_layer | lti_layer

# train-test split
# test_size: 0.25

tensorboard: False  # Save model information for analysis in tensorboard

# scaling bounds for mu
desired_bounds: [0, 1]  # desired bounds after scaling for u and mu

# time extrapolation
trunc_time_ratio: 1  # ratio of time steps to be truncated for time extrapolation
validation: False  # ratio of data to be used for validation

n_simulations_per_parameter_set: 1

scale_x: False
domain_split_vals: [1,1]

# %% identification settings
l1: 0.0000000001  # L1 regularizationl2: 0  # L2 regularization
l2: 0
n_epochs: 1 #2500 # number of epochs
batch_size: 64  # batch size
layer_sizes_ph: # layer sizes
  - 16  # first layer
  - 32  # second layer
  - 64  # third layer
activation_ph: selu  # activation function
lr: 0.000025  # learning rate

# matrix interpolation
ansatz: linear   # linear | cubic (only for 1D and 2D) | nearest
matrix_type: ph   # ph | lti

matrix_color_limits:
  - -1.5
  - 1.5
  - -0.005
  - 0.005
  - -0.01
  - 0.25
  - -1.5
  - 1.5

matrix_error_limits:
  - 0.025
  - 0.005
  - 0.01
  - 0.01 