model_name: msd

experiment: msd_Halton # name of the experiment
sim_name: MSD_Qeye_ph_input_siso.npz # name of data  msd_state_ICrand_Qeye_autonomous_n3_m4.npz
load_network: False  # train the network or load the last pre-trained one

seed: 123  # For reproducibility

setup_matplotlib: False

# train-test split
test_size: 0.25

tensorboard: False  # Save model information for analysis in tensorboard

# scaling bounds for mu
desired_bounds: [0, 1]  # desired bounds after scaling for u and mu

# %% identification settings
l1: 0.0000001  # L1 regularization
l2: 0  # L2 regularization
n_epochs: 2000  # number of epochs
batch_size: 64  # batch size
layer_sizes_ph: # layer sizes
  - 16  # first layer
  - 16  # second layer
  - 16  # third layer
  - 16  # third layer
activation_ph: elu  # activation function
lr: 0.0005  # learning rate
